services:
    test-website:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: test-website
        hostname: test-website
        ports:
            - "8085:8085"
        healthcheck:
            test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
            timeout: 10s
            retries: 5
            start_period: 5s
